const REGISTER_USER = 'REGISTER_USER';
const GET_EXPENSES = 'GET_EXPENSES';
const GET_EXPENSE_CATEGORIES = 'GET_EXPENSE_CATEGORIES';

export default {
  REGISTER_USER,
  GET_EXPENSES,
  GET_EXPENSE_CATEGORIES
};