const REGISTER_USER = 'REGISTER_USER';
const GET_EXPENSES = 'GET_EXPENSES';
const PUSH_EXPENSE = 'PUSH_EXPENSE';
const GET_EXPENSE_CATEGORIES = 'GET_EXPENSE_CATEGORIES';
const UPDATE_EXPENSES_FILTER = 'UPDATE_EXPENSES_FILTER';

export default {
  REGISTER_USER,
  GET_EXPENSES,
  PUSH_EXPENSE,
  UPDATE_EXPENSES_FILTER,
  GET_EXPENSE_CATEGORIES
};