const REGISTER_USER = 'REGISTER_USER';
const GET_EXPENSES = 'GET_EXPENSES';
const PUSH_EXPENSE = 'PUSH_EXPENSE';
const GET_EXPENSE_CATEGORIES = 'GET_EXPENSE_CATEGORIES';

export default {
  REGISTER_USER,
  GET_EXPENSES,
  PUSH_EXPENSE,
  GET_EXPENSE_CATEGORIES
};